# discord-bot-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: your-docker-username/discord-bot-image:latest
        ports:
        - containerPort: 80
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: bot-token
---
# discord-bot-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: discord-bot
spec:
  selector:
    app: discord-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
